/* tslint:disable */
/* eslint-disable */
/**
 * EdoSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ClientV1Dto,
  ClientV2Dto,
} from '../models/index';
import {
    ClientV1DtoFromJSON,
    ClientV1DtoToJSON,
    ClientV2DtoFromJSON,
    ClientV2DtoToJSON,
} from '../models/index';

export interface ClientsCreateRequest {
    clientV2Dto?: ClientV2Dto;
}

export interface ClientsDeleteRequest {
    id: number;
}

export interface ClientsGetByIdRequest {
    id: number;
}

export interface ClientsUpdateRequest {
    id: number;
    clientV2Dto?: ClientV2Dto;
}

/**
 * 
 */
export class ClientsApi extends runtime.BaseAPI {

    /**
     */
    async clientsCreateRaw(requestParameters: ClientsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClientV2Dto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/Clients`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ClientV2DtoToJSON(requestParameters['clientV2Dto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClientV2DtoFromJSON(jsonValue));
    }

    /**
     */
    async clientsCreate(requestParameters: ClientsCreateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClientV2Dto> {
        const response = await this.clientsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async clientsDeleteRaw(requestParameters: ClientsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling clientsDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/Clients/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async clientsDelete(requestParameters: ClientsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.clientsDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async clientsGetByIdRaw(requestParameters: ClientsGetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClientV2Dto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling clientsGetById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/Clients/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClientV2DtoFromJSON(jsonValue));
    }

    /**
     */
    async clientsGetById(requestParameters: ClientsGetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClientV2Dto> {
        const response = await this.clientsGetByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async clientsGetV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ClientV1Dto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/Clients`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ClientV1DtoFromJSON));
    }

    /**
     */
    async clientsGetV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ClientV1Dto>> {
        const response = await this.clientsGetV1Raw(initOverrides);
        return await response.value();
    }

    /**
     */
    async clientsUpdateRaw(requestParameters: ClientsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling clientsUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/Clients/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ClientV2DtoToJSON(requestParameters['clientV2Dto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async clientsUpdate(requestParameters: ClientsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.clientsUpdateRaw(requestParameters, initOverrides);
    }

}
