/* tslint:disable */
/* eslint-disable */
/**
 * EdoSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DocumentTypeV1Dto,
  DocumentTypeV2Dto,
} from '../models/index';
import {
    DocumentTypeV1DtoFromJSON,
    DocumentTypeV1DtoToJSON,
    DocumentTypeV2DtoFromJSON,
    DocumentTypeV2DtoToJSON,
} from '../models/index';

export interface DocTypesCreateRequest {
    documentTypeV2Dto?: DocumentTypeV2Dto;
}

export interface DocTypesDeleteRequest {
    id: number;
}

export interface DocTypesGetByIdRequest {
    id: number;
}

export interface DocTypesUpdateRequest {
    id: number;
    documentTypeV2Dto?: DocumentTypeV2Dto;
}

/**
 * 
 */
export class DocumentTypesApi extends runtime.BaseAPI {

    /**
     */
    async docTypesCreateRaw(requestParameters: DocTypesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DocumentTypeV2Dto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/document-types`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DocumentTypeV2DtoToJSON(requestParameters['documentTypeV2Dto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DocumentTypeV2DtoFromJSON(jsonValue));
    }

    /**
     */
    async docTypesCreate(requestParameters: DocTypesCreateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DocumentTypeV2Dto> {
        const response = await this.docTypesCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async docTypesDeleteRaw(requestParameters: DocTypesDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling docTypesDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/document-types/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async docTypesDelete(requestParameters: DocTypesDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.docTypesDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async docTypesGetByIdRaw(requestParameters: DocTypesGetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DocumentTypeV2Dto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling docTypesGetById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/document-types/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DocumentTypeV2DtoFromJSON(jsonValue));
    }

    /**
     */
    async docTypesGetById(requestParameters: DocTypesGetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DocumentTypeV2Dto> {
        const response = await this.docTypesGetByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async docTypesGetV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DocumentTypeV1Dto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/document-types`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DocumentTypeV1DtoFromJSON));
    }

    /**
     */
    async docTypesGetV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DocumentTypeV1Dto>> {
        const response = await this.docTypesGetV1Raw(initOverrides);
        return await response.value();
    }

    /**
     */
    async docTypesUpdateRaw(requestParameters: DocTypesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling docTypesUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/document-types/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: DocumentTypeV2DtoToJSON(requestParameters['documentTypeV2Dto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async docTypesUpdate(requestParameters: DocTypesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.docTypesUpdateRaw(requestParameters, initOverrides);
    }

}
