/* tslint:disable */
/* eslint-disable */
/**
 * EdoSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SignedDocumentV1Dto,
  SignedDocumentV2Dto,
} from '../models/index';
import {
    SignedDocumentV1DtoFromJSON,
    SignedDocumentV1DtoToJSON,
    SignedDocumentV2DtoFromJSON,
    SignedDocumentV2DtoToJSON,
} from '../models/index';

export interface SignedDocsDeleteRequest {
    id: number;
}

export interface SignedDocsGetByIdRequest {
    id: number;
}

/**
 * 
 */
export class SignedDocumentsApi extends runtime.BaseAPI {

    /**
     */
    async signedDocsDeleteRaw(requestParameters: SignedDocsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling signedDocsDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/signed-documents/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async signedDocsDelete(requestParameters: SignedDocsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.signedDocsDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async signedDocsGetByIdRaw(requestParameters: SignedDocsGetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignedDocumentV2Dto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling signedDocsGetById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/signed-documents/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SignedDocumentV2DtoFromJSON(jsonValue));
    }

    /**
     */
    async signedDocsGetById(requestParameters: SignedDocsGetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignedDocumentV2Dto> {
        const response = await this.signedDocsGetByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async signedDocsGetV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SignedDocumentV1Dto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/signed-documents`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SignedDocumentV1DtoFromJSON));
    }

    /**
     */
    async signedDocsGetV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SignedDocumentV1Dto>> {
        const response = await this.signedDocsGetV1Raw(initOverrides);
        return await response.value();
    }

}
