/* tslint:disable */
/* eslint-disable */
/**
 * EdoSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientV1Dto
 */
export interface ClientV1Dto {
    /**
     * 
     * @type {number}
     * @memberof ClientV1Dto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ClientV1Dto
     */
    name?: string | null;
}

/**
 * Check if a given object implements the ClientV1Dto interface.
 */
export function instanceOfClientV1Dto(value: object): value is ClientV1Dto {
    return true;
}

export function ClientV1DtoFromJSON(json: any): ClientV1Dto {
    return ClientV1DtoFromJSONTyped(json, false);
}

export function ClientV1DtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientV1Dto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ClientV1DtoToJSON(json: any): ClientV1Dto {
    return ClientV1DtoToJSONTyped(json, false);
}

export function ClientV1DtoToJSONTyped(value?: ClientV1Dto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

