/* tslint:disable */
/* eslint-disable */
/**
 * EdoSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientV2Dto
 */
export interface ClientV2Dto {
    /**
     * 
     * @type {number}
     * @memberof ClientV2Dto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ClientV2Dto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ClientV2Dto
     */
    email?: string | null;
}

/**
 * Check if a given object implements the ClientV2Dto interface.
 */
export function instanceOfClientV2Dto(value: object): value is ClientV2Dto {
    return true;
}

export function ClientV2DtoFromJSON(json: any): ClientV2Dto {
    return ClientV2DtoFromJSONTyped(json, false);
}

export function ClientV2DtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientV2Dto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function ClientV2DtoToJSON(json: any): ClientV2Dto {
    return ClientV2DtoToJSONTyped(json, false);
}

export function ClientV2DtoToJSONTyped(value?: ClientV2Dto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'email': value['email'],
    };
}

