/* tslint:disable */
/* eslint-disable */
/**
 * EdoSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentTypeV2Dto
 */
export interface DocumentTypeV2Dto {
    /**
     * 
     * @type {number}
     * @memberof DocumentTypeV2Dto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DocumentTypeV2Dto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentTypeV2Dto
     */
    description?: string | null;
}

/**
 * Check if a given object implements the DocumentTypeV2Dto interface.
 */
export function instanceOfDocumentTypeV2Dto(value: object): value is DocumentTypeV2Dto {
    return true;
}

export function DocumentTypeV2DtoFromJSON(json: any): DocumentTypeV2Dto {
    return DocumentTypeV2DtoFromJSONTyped(json, false);
}

export function DocumentTypeV2DtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentTypeV2Dto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function DocumentTypeV2DtoToJSON(json: any): DocumentTypeV2Dto {
    return DocumentTypeV2DtoToJSONTyped(json, false);
}

export function DocumentTypeV2DtoToJSONTyped(value?: DocumentTypeV2Dto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
    };
}

