/* tslint:disable */
/* eslint-disable */
/**
 * EdoSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignedDocumentV1Dto
 */
export interface SignedDocumentV1Dto {
    /**
     * 
     * @type {number}
     * @memberof SignedDocumentV1Dto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SignedDocumentV1Dto
     */
    fileName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignedDocumentV1Dto
     */
    clientName?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof SignedDocumentV1Dto
     */
    isSigned?: boolean;
}

/**
 * Check if a given object implements the SignedDocumentV1Dto interface.
 */
export function instanceOfSignedDocumentV1Dto(value: object): value is SignedDocumentV1Dto {
    return true;
}

export function SignedDocumentV1DtoFromJSON(json: any): SignedDocumentV1Dto {
    return SignedDocumentV1DtoFromJSONTyped(json, false);
}

export function SignedDocumentV1DtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignedDocumentV1Dto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'fileName': json['fileName'] == null ? undefined : json['fileName'],
        'clientName': json['clientName'] == null ? undefined : json['clientName'],
        'isSigned': json['isSigned'] == null ? undefined : json['isSigned'],
    };
}

export function SignedDocumentV1DtoToJSON(json: any): SignedDocumentV1Dto {
    return SignedDocumentV1DtoToJSONTyped(json, false);
}

export function SignedDocumentV1DtoToJSONTyped(value?: SignedDocumentV1Dto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'fileName': value['fileName'],
        'clientName': value['clientName'],
        'isSigned': value['isSigned'],
    };
}

