/* tslint:disable */
/* eslint-disable */
/**
 * EdoSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignedDocumentV2Dto
 */
export interface SignedDocumentV2Dto {
    /**
     * 
     * @type {number}
     * @memberof SignedDocumentV2Dto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SignedDocumentV2Dto
     */
    fileName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignedDocumentV2Dto
     */
    clientName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignedDocumentV2Dto
     */
    documentTypeName?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof SignedDocumentV2Dto
     */
    uploadedAt?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof SignedDocumentV2Dto
     */
    isSigned?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof SignedDocumentV2Dto
     */
    signedAt?: Date | null;
}

/**
 * Check if a given object implements the SignedDocumentV2Dto interface.
 */
export function instanceOfSignedDocumentV2Dto(value: object): value is SignedDocumentV2Dto {
    return true;
}

export function SignedDocumentV2DtoFromJSON(json: any): SignedDocumentV2Dto {
    return SignedDocumentV2DtoFromJSONTyped(json, false);
}

export function SignedDocumentV2DtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignedDocumentV2Dto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'fileName': json['fileName'] == null ? undefined : json['fileName'],
        'clientName': json['clientName'] == null ? undefined : json['clientName'],
        'documentTypeName': json['documentTypeName'] == null ? undefined : json['documentTypeName'],
        'uploadedAt': json['uploadedAt'] == null ? undefined : (new Date(json['uploadedAt'])),
        'isSigned': json['isSigned'] == null ? undefined : json['isSigned'],
        'signedAt': json['signedAt'] == null ? undefined : (new Date(json['signedAt'])),
    };
}

export function SignedDocumentV2DtoToJSON(json: any): SignedDocumentV2Dto {
    return SignedDocumentV2DtoToJSONTyped(json, false);
}

export function SignedDocumentV2DtoToJSONTyped(value?: SignedDocumentV2Dto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'fileName': value['fileName'],
        'clientName': value['clientName'],
        'documentTypeName': value['documentTypeName'],
        'uploadedAt': value['uploadedAt'] == null ? value['uploadedAt'] : value['uploadedAt'].toISOString(),
        'isSigned': value['isSigned'],
        'signedAt': value['signedAt'] == null ? value['signedAt'] : value['signedAt'].toISOString(),
    };
}

